### ISSUE TITLE
Elegir colores y crear navbar, footer y cuerpo de la página.

### ISSUE THREAD

**Issue by AIT-4** [AIT-4/trabajo_practico_argentina_programa#1]
Para elegir colores:
https://colorhub.vercel.app/select-palette

**Comment by AIT-4** [comment]
Seleccione esta paleta de colores:
```CSS
  --dark-color: #164E63;
  --mid-color: #41CBBF;
  --light-color: #F8FAFC;
  --gray-color: #BEC9DF;
```
Empece a desarrollar como la landing page #3:

![imagen](https://user-images.githubusercontent.com/84646758/230695938-6ca330f3-d805-4bc5-9560-219e4a58ace3.png)

**Comment by martu2912** [comment]
>  <nav class="navbar navbar-expand-lg bg-body-tertiary color-dark p-3"
            style="background-color: #164E63 !important; color: #41CBBF !important;">

**Comment by martu2912** [comment]
Tenia duda si en el nav agregar por ejemplo: Servicios, FAQ, Testimonios, Contacto. Algunas landing page no tienen nada pero otras tienen alguno de esos. 
También eso que decís de que cambie de color la barra del nav, no se si va en una landing page porque como que no tiene mucho contenido como para deslizar.

**Comment by AIT-4** [comment]
Tiene sentido lo que decis. Podemos ver cuando quede terminada a ver si lo mantenemos o no. También se le pueden agregar espacios para que quede mas acomodado. Le sabe dar buena imagen.
