### ISSUE TITLE
Ordenar navbar: crear logo y nombre de la empresa.

### ISSUE THREAD

**Issue by AIT-4** [AIT-4/trabajo_practico_argentina_programa#2]
Se necesitaría crear logo y nombre de la empresa. Se puede realizar que cuando se scrolee por la pagina el navbar cambie de color al "light color" (#F8FAFC) cuando llegue al section 2.

**Comment by joseluis-b89** [comment]
Ya se agrego el logo y el nombre de la empresa. Faltaria agregar la funcion de que cuando se scrolee por la pagina, el navbar cambie de color al "light color" (#F8FAFC) cuando llegue al section 2.
