### ISSUE TITLE
Section 1: Crear formulario y texto que explique el formulario.

### ISSUE THREAD

**Issue by AIT-4** [AIT-4/trabajo_practico_argentina_programa#3]
Crear formulario con funcionamiento como explica en la consigna. También se necesita texto que explique el formulario en la columna 1. También se puede poner algún tipo de lema.

**Comment by martu2912** [comment]
El formulario como lo hacemos? Porque en la consigna dice: A modo de asistente (Wizard), validación de campo, Generación de resumen y exportación a PDF. De eso no vimos nada. Decís que lo hagamos sin todo eso? o me pongo a investigar para ver como hacerlo?

**Comment by AIT-4** [comment]
Creo que lo que conviene es que primero este todo armado y después hacemos el wizard.
